# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Download quandl data
    init: |
      pip install quandl
      read -p "Enter Your quandl API Token(free for login): " QUANDL_TOKEN
      sed -e s/MY_TOKEN/$QUANDL_TOKEN/g ./quandl_template.py > ./quandle_execute.py
      python quandle_execute.py


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
